name: Python Linting and Formatting

on:
  push:
    branches: [main]
    # Only on these paths so that something like a README update doesn't trigger it
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/lint.yml"
  workflow_dispatch:

# Cancel existing executions when new commits are pushed onto the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    lint-and-format:
      runs-on: ubuntu-latest
      timeout-minutes: 60
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up uv
          uses: astral-sh/setup-uv@v4
          with:
            version: "0.5.7"
        - name: Set up Python
          run: uv python install 3.11
        - name: Install project
          run: |
            uv sync --dev
        - name: Lint with ruff
          run: |
            uv run ruff check .
        - name: Format with ruff
          run: |
            uv run ruff format --check .
        - name: Check with mypy
          run: |
            uv run mypy .