name: Python Linting and Formatting

on:
  push:
    branches: [main]
    # Only on these paths so that something like a README update doesn't trigger it
    paths:
      - "**.py"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/lint.yml"
  workflow_dispatch:

# Cancel existing executions when new commits are pushed onto the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
    lint-and-format:
      runs-on: ubuntu-latest
      timeout-minutes: 60
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up Python (and Cache CI dependencies)
          uses: actions/setup-python@v3
          with:
            python-version: "3.9"
        - name: Upgrade pip, install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Check with isort
          run: |
            isort . --check --diff
        - name: Check with black
          run: |
            black . --check
        - name: Check with flake8
          run: |
            flake8 .
        - name: Check with mypy
          run: |
            mypy .